package za.co.telkom;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2019-04-10T11:11:23.441+05:30
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "Billing", 
                  wsdlLocation = "classpath:wsdl/Billing-EI-ESB.wsdl",
                  targetNamespace = "http://www.telkom.co.za") 
public class Billing extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.telkom.co.za", "Billing");
    public final static QName BillingSoap = new QName("http://www.telkom.co.za", "BillingSoap");
    static {
        URL url = Billing.class.getClassLoader().getResource("wsdl/Billing-EI-ESB.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(Billing.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/Billing-EI-ESB.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public Billing(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Billing(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Billing() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Billing(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Billing(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Billing(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns BillingSoap
     */
    @WebEndpoint(name = "BillingSoap")
    public BillingSoap getBillingSoap() {
        return super.getPort(BillingSoap, BillingSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillingSoap
     */
    @WebEndpoint(name = "BillingSoap")
    public BillingSoap getBillingSoap(WebServiceFeature... features) {
        return super.getPort(BillingSoap, BillingSoap.class, features);
    }

}
