
package za.co.telkom;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2019-04-10T11:11:23.409+05:30
 * Generated source version: 3.0.4
 */

@WebFault(name = "check3DSEnrolmentResponse", targetNamespace = "http://www.telkom.co.za")
public class Check3DSEnrolmentSoapOut extends Exception {
    
    private za.co.telkom.Check3DSEnrolmentResponse check3DSEnrolmentResponse;

    public Check3DSEnrolmentSoapOut() {
        super();
    }
    
    public Check3DSEnrolmentSoapOut(String message) {
        super(message);
    }
    
    public Check3DSEnrolmentSoapOut(String message, Throwable cause) {
        super(message, cause);
    }

    public Check3DSEnrolmentSoapOut(String message, za.co.telkom.Check3DSEnrolmentResponse check3DSEnrolmentResponse) {
        super(message);
        this.check3DSEnrolmentResponse = check3DSEnrolmentResponse;
    }

    public Check3DSEnrolmentSoapOut(String message, za.co.telkom.Check3DSEnrolmentResponse check3DSEnrolmentResponse, Throwable cause) {
        super(message, cause);
        this.check3DSEnrolmentResponse = check3DSEnrolmentResponse;
    }

    public za.co.telkom.Check3DSEnrolmentResponse getFaultInfo() {
        return this.check3DSEnrolmentResponse;
    }
}
