
package za.co.telkom;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2019-04-10T11:11:23.413+05:30
 * Generated source version: 3.0.4
 */

@WebFault(name = "rechargeResponse", targetNamespace = "http://www.telkom.co.za")
public class RechargeSoapOut extends Exception {
    
    private za.co.telkom.RechargeResponse rechargeResponse;

    public RechargeSoapOut() {
        super();
    }
    
    public RechargeSoapOut(String message) {
        super(message);
    }
    
    public RechargeSoapOut(String message, Throwable cause) {
        super(message, cause);
    }

    public RechargeSoapOut(String message, za.co.telkom.RechargeResponse rechargeResponse) {
        super(message);
        this.rechargeResponse = rechargeResponse;
    }

    public RechargeSoapOut(String message, za.co.telkom.RechargeResponse rechargeResponse, Throwable cause) {
        super(message, cause);
        this.rechargeResponse = rechargeResponse;
    }

    public za.co.telkom.RechargeResponse getFaultInfo() {
        return this.rechargeResponse;
    }
}
