
package za.co.telkom;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2019-04-10T11:11:23.404+05:30
 * Generated source version: 3.0.4
 */

@WebFault(name = "validateAccountResponse", targetNamespace = "http://www.telkom.co.za")
public class ValidateAccountSoapOut extends Exception {
    
    private za.co.telkom.ValidateAccountResponse validateAccountResponse;

    public ValidateAccountSoapOut() {
        super();
    }
    
    public ValidateAccountSoapOut(String message) {
        super(message);
    }
    
    public ValidateAccountSoapOut(String message, Throwable cause) {
        super(message, cause);
    }

    public ValidateAccountSoapOut(String message, za.co.telkom.ValidateAccountResponse validateAccountResponse) {
        super(message);
        this.validateAccountResponse = validateAccountResponse;
    }

    public ValidateAccountSoapOut(String message, za.co.telkom.ValidateAccountResponse validateAccountResponse, Throwable cause) {
        super(message, cause);
        this.validateAccountResponse = validateAccountResponse;
    }

    public za.co.telkom.ValidateAccountResponse getFaultInfo() {
        return this.validateAccountResponse;
    }
}
